### ISSUE TITLE
Own Bonus

### ISSUE THREAD

**Issue by Topich** [jmaupoux/lotofoot-v2#134]
Make the possibility each day for each player to select one match.
This match will be a match bonus (points X 2).
The real match bonus can't be chosen.

**Comment by jmaupoux** [comment]
What happen to statistics on bonus ? Count 2 bonuses each day ?

**Comment by jmaupoux** [comment]
Test and update rules please

**Comment by Topich** [comment]
ok j'ai testé faut que je fasse du css pour le rendre plus mignon

**Comment by Topich** [comment]
ok
