### ISSUE TITLE
Add avatar

### ISSUE THREAD

**Issue by Topich** [jmaupoux/lotofoot-v2#137]
Visible when the user add comments.
Can be change in profile.html

**Comment by jmaupoux** [comment]
Are you OK for a gravatar email ?
Avoid image storing & sizing

**Comment by Topich** [comment]
How does it work ?

**Comment by jmaupoux** [comment]
need an acc in https://fr.gravatar.com/, up an avatar then reference email account in lotofoot

**Comment by Topich** [comment]
I did it there's nothing new when I leave a comment...
Do I have to change the code ? :)

**Comment by jmaupoux** [comment]
Please note : default avatar won't work in localhost
