### ISSUE TITLE
ADMIN : Allow match deadline modification after creation

### ISSUE THREAD

**Issue by jmaupoux** [jmaupoux/lotofoot-v2#139]

**Comment by Topich** [comment]
There is an error when I vote for the second time after new deadline :

FatalErrorException: Error: Call to a member function getId() on a non-object in C:\zend-eclipse-php\workspace\lotofoot-v2\Symfony\src\Lotofootv2\Bundle\Controller\User\League\VoteController.php line 186

**Comment by Topich** [comment]
There is a second error : When I go on http://localhost/lotofoot-v2/app_dev.php/admin/league/day
I can't change a second time and "the votes are closed" even the new deadline is not passed

**Comment by jmaupoux** [comment]
Can get your error.
What did u do ?

**Comment by Topich** [comment]
There's a chance that I put an obsolete time...

**Comment by Topich** [comment]
There's another error with my own bonus.
It's changing after date modification

**Comment by Topich** [comment]
Ok i don't know what happend yesterday, but now it works

There's maybe a doubt...
en français parce que c'est compliqué : quand tu modifies une date au delà de la date de cloture de la journée, j'ai l'impression que tu n'as pas pris en compte la nouvelle date de cloture de la journee...

Ex: tous les match sont à 20:30 et que tu en changes un pour le mettre à 20:45, à 20:37, si tu vas sur http://localhost/lotofoot-v2/app_dev.php/admin/league/day, les votes sont clos alors que potentiellement tu pourrais à nouveau la reculer jusqu'à 21h...

**Comment by jmaupoux** [comment]
ok, test please

**Comment by Topich** [comment]
ok
