### ISSUE TITLE
Send mail to the punchliner after day corrected

### ISSUE THREAD

**Issue by jmaupoux** [jmaupoux/lotofoot-v2#95]

**Comment by Topich** [comment]
can't test it in localhost...

**Comment by jmaupoux** [comment]
You can : 
- create a day
- set the lotofoot.mail password in Symfony\app\config\parameters.yml, 
- ensure YOU are the punchliner when correcting the day, 
- test. 

You have to receive the mail. 

- **Then remove the password thx =)**
